export const googleDocsColors: { hex: string; name: string }[] = [
  { hex: "#000000", name: "Black" },
  { hex: "#434343", name: "Dark Gray 4" },
  { hex: "#666666", name: "Dark Gray 3" },
  { hex: "#999999", name: "Dark Gray 2" },
  { hex: "#b7b7b7", name: "Dark Gray 1" },
  { hex: "#cccccc", name: "Gray" },
  { hex: "#d9d9d9", name: "Light Gray 1" },
  { hex: "#efefef", name: "Light Gray 2" },
  { hex: "#f3f3f3", name: "Light Gray 3" },
  { hex: "#ffffff", name: "White" },

  { hex: "#980000", name: "Dark Red 2" },
  { hex: "#ff0000", name: "Red" },
  { hex: "#ff9900", name: "Orange" },
  { hex: "#ffff00", name: "Yellow" },
  { hex: "#00ff00", name: "Lime" },
  { hex: "#00ffff", name: "Cyan" },
  { hex: "#4a86e8", name: "Blue" },
  { hex: "#0000ff", name: "Dark Blue" },
  { hex: "#9900ff", name: "Purple" },
  { hex: "#ff00ff", name: "Magenta" },

  { hex: "#e6b8af", name: "Pale Red" },
  { hex: "#f4cccc", name: "Very Light Red" },
  { hex: "#f9c99c", name: "Peach" },
  { hex: "#fff2cc", name: "Light Yellow" },
  { hex: "#d9ead3", name: "Light Green" },
  { hex: "#d0e0e3", name: "Light Teal" },
  { hex: "#c9daf8", name: "Light Blue" },
  { hex: "#cfe2f3", name: "Pale Blue" },
  { hex: "#d9d2e9", name: "Lavender" },
  { hex: "#ead1dc", name: "Light Pink" },

  { hex: "#dd7e6b", name: "Soft Red" },
  { hex: "#ea9999", name: "Pink" },
  { hex: "#f9cb9c", name: "Soft Orange" },
  { hex: "#ffe599", name: "Soft Yellow" },
  { hex: "#b6d7a8", name: "Soft Green" },
  { hex: "#a2c4c9", name: "Soft Teal" },
  { hex: "#a4c2f4", name: "Sky Blue" },
  { hex: "#9fc5e8", name: "Soft Blue" },
  { hex: "#b4a7d6", name: "Soft Purple" },
  { hex: "#d5a6bd", name: "Soft Pink" },

  { hex: "#cc4125", name: "Rust" },
  { hex: "#e06666", name: "Coral" },
  { hex: "#f6b26b", name: "Amber" },
  { hex: "#ffd966", name: "Gold" },
  { hex: "#93c47d", name: "Mid Green" },
  { hex: "#76a5af", name: "Steel Blue" },
  { hex: "#6d9eeb", name: "Cornflower" },
  { hex: "#6fa8dc", name: "Sky" },
  { hex: "#8e7cc3", name: "Lavender Purple" },
  { hex: "#c27ba0", name: "Rose" },

  { hex: "#a61c00", name: "Brick Red" },
  { hex: "#cc0000", name: "Strong Red" },
  { hex: "#e69138", name: "Orange Brown" },
  { hex: "#f1c232", name: "Bright Yellow" },
  { hex: "#6aa84f", name: "Fresh Green" },
  { hex: "#45818e", name: "Cool Teal" },
  { hex: "#3c78d8", name: "Vivid Blue" },
  { hex: "#3d85c6", name: "Ocean Blue" },
  { hex: "#674ea7", name: "Violet" },
  { hex: "#a64d79", name: "Dusty Pink" },

  { hex: "#85200c", name: "Dark Brick" },
  { hex: "#990000", name: "Dark Red" },
  { hex: "#b45f06", name: "Brown" },
  { hex: "#bf9000", name: "Moss Yellow" },
  { hex: "#38761d", name: "Forest Green" },
  { hex: "#134f5c", name: "Deep Teal" },
  { hex: "#1155cc", name: "Strong Blue" },
  { hex: "#0b5394", name: "Dark Ocean" },
  { hex: "#351c75", name: "Deep Purple" },
  { hex: "#741b47", name: "Plum" },

  { hex: "#5b0f00", name: "Very Dark Brick" },
  { hex: "#660000", name: "Very Dark Red" },
  { hex: "#783f04", name: "Dark Brown" },
  { hex: "#7f6000", name: "Dark Gold" },
  { hex: "#274e13", name: "Dark Forest" },
  { hex: "#0c343d", name: "Dark Teal" },
  { hex: "#1c4587", name: "Dark Blue 2" },
  { hex: "#073763", name: "Midnight Blue" },
  { hex: "#20124d", name: "Royal Purple" },
  { hex: "#4c1130", name: "Dark Rose" },
];
